atomf.bashlib: also glob - if no revision
Most -[0-9]* cases are handled but -[0-9]- was overlooked, qatom
also seem to have issues with it right now (wrongly split).

$ qatom sys-firmware/iwl3160-7260-bt-ucode
sys-firmware iwl3160 7260-bt-ucode
$ atomf sys-firmware/iwl3160-7260-bt-ucode
Error: 'sys-firmware/iwl3160-7260-bt-ucode' is an invalid atom (atomf)

This now reports the whole PN and a properly missing PV